import { Link } from "@tanstack/react-router";
import { ArrowLeft, ArrowRight } from "lucide-react";
import { projects, type Project } from "@/data/projects";
import { Button } from "@/components/ui/button";
import { SectionLabel } from "./Sections";

export function CaseStudy({project}:{project:Project}){const i=projects.findIndex(p=>p.slug===project.slug);const next=projects[(i+1)%projects.length];if(!next)return null;return <>
<section className="case-hero editorial-grid"><Link to="/work" className="back-link"><ArrowLeft/> ALL WORK</Link><p className="case-number">PROJECT {project.number}</p><h1>{project.title}</h1><div className="case-meta"><div><span>ROLE</span><p>UI/UX Designer / Front-End Developer</p></div><div><span>DISCIPLINE</span><p>{project.category}</p></div></div></section>
<div className="case-main-image" data-cursor="view"><img src={project.image} alt={`${project.title} primary interface mockups`} width={project.dimensions[0]} height={project.dimensions[1]}/></div>
<section className="case-overview editorial-grid"><SectionLabel>OVERVIEW</SectionLabel><h2>{project.description}</h2><div><span>CHALLENGE</span><p>{project.challenge}</p></div><div><span>OBJECTIVE</span><p>{project.objective}</p></div></section>
<section className="case-process dark-band"><div><SectionLabel>RESEARCH / DISCOVERY</SectionLabel><h2>FIND THE SIGNAL<br/>BEFORE THE STYLE.</h2></div><div className="case-process-grid"><article><span>01</span><h3>USER FLOW</h3><p>Mapped the essential journeys, decision points and content priorities before committing to visual detail.</p></article><article><span>02</span><h3>WIREFRAMES</h3><p>Built low-fidelity structures to test hierarchy, density and responsive behavior across key screens.</p></article><article><span>03</span><h3>VISUAL DESIGN</h3><p>Developed an adaptable visual language with a clear type scale, purposeful color and consistent interaction patterns.</p></article></div></section>
<section className="case-gallery editorial-grid"><div><SectionLabel>DESIGN SYSTEM</SectionLabel><h2>CONSISTENCY<br/>AT EVERY SCALE.</h2></div><figure className="gallery-large"><img src={project.image} alt={`${project.title} design system screens`} loading="lazy" width={project.dimensions[0]} height={project.dimensions[1]}/></figure><div className="system-swatch"><span>TYPE / 01</span><strong>Aa</strong><p>Clear hierarchy<br/>Flexible scale</p></div><div className="system-swatch accent"><span>COLOR / 02</span><strong>●</strong><p>Focused accents<br/>Accessible contrast</p></div></section>
<section className="case-development"><SectionLabel>DEVELOPMENT</SectionLabel><div><h2>DESIGNED TO<br/>WORK IN CODE.</h2><p>The interface was considered as a responsive system rather than a fixed composition. Components, states and spacing adapt deliberately from desktop to mobile.</p></div><div className="device-crop"><img src={project.image} alt={`${project.title} responsive presentation`} loading="lazy" width={project.dimensions[0]} height={project.dimensions[1]}/></div></section>
<section className="case-result editorial-grid"><SectionLabel>FINAL RESULT</SectionLabel><h2>{project.result}</h2><div><span>KEY LEARNINGS</span><p>Strong outcomes begin with hierarchy. Early structural decisions made later visual and development choices more coherent.</p></div><div><span>TECH STACK</span><p>{project.tech.join(" / ")}</p></div></section>
<section className="next-project dark-band"><p>NEXT PROJECT</p><Link to="/work/$slug" params={{slug:next.slug}}><span>{next.number}</span>{next.title}<ArrowRight/></Link></section></>}
